# Generated by Django 5.2.2 on 2025-06-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('photo', models.ImageField(upload_to='employee_photos/')),
                ('age', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
